export type Influencer = {
  name: string;
  specialty: string;
  image: string;
  stacks: string[];
  bio?: string;
  supplements?: string[]; // full list for profile page
  cardSupplements?: string[]; // curated subset for list card "Supplement Breakdown"
  coveredCategories?: string[];
  sns?: {
    instagram?: string; // full URL or handle
    x?: string; // full URL
  };
};

export const influencers: Influencer[] = [
  {
    name: "Bryan Johnson",
    specialty: "Longevity pioneer (Blueprint)",
    image: "/people/bryan.jpg",
    stacks: [
      "Blueprint Core",
      "Blueprint Cardio",
      "Blueprint Gut",
      "Blueprint Performance",
      "Blueprint Anti-inflammatory",
      "Blueprint Vision",
    ],
    supplements: [
      "Collagen Protein",
      "Creatine",
      "Prebiotic GOS",
      "Longevity Protein",
      "Blueprint Essentials (Multivitamin)",
      "Blueprint Soft Gel (Vision)",
      "NAC + Ginger + Curcumin",
      "Red Yeast Rice + Garlic",
      "Omega-3",
      "Aged Garlic",
      "ProButyrate",
      "Heme Iron",
      "NMN or NR",
    ],
    cardSupplements: ["Creatine", "NMN", "Spermidine", "Magnesium", "Omega-3"],
    coveredCategories: [
      "Energy Boost",
      "Longevity & Immune",
      "Sleep Optimization",
      "Cognitive Enhancement",
      "Beauty / Inner Glow",
      "Metabolic & Weight",
    ],
    bio: `A tech entrepreneur turned longevity pioneer, Johnson has gained international attention for his Blueprint protocol—a comprehensive, data-driven approach to age reversal that combines rigorous self-experimentation with substantial financial investment in cutting-edge anti-aging research.`,
    sns: {
      instagram: "https://www.instagram.com/bryanjohnson_",
      x: "https://twitter.com/bryan_johnson",
    },
  },
  {
    name: "David Sinclair",
    specialty: "Harvard professor & longevity researcher",
    image: "/people/david.jpg",
    stacks: [
      "Sinclair Longevity Core",
      "Sinclair NAD+ & Autophagy",
      "Sinclair Polyphenols",
      "Sinclair Cardio & Metabolic",
    ],
    supplements: [
      "NMN",
      "Resveratrol",
      "Vitamin D3 + K2",
      "Quercetin",
      "Fisetin",
      "Alpha-lipoic acid",
      "Spermidine",
      "Omega-3",
    ],
    cardSupplements: ["NMN", "Resveratrol", "Metformin (Rx)", "Vitamin D + K2"],
    coveredCategories: [
      "Longevity & Immune",
      "Metabolic & Weight",
      "Sleep Optimization",
      "Cognitive Enhancement",
      "Beauty / Inner Glow",
      "Energy Boost",
    ],
    bio: `A pioneering Harvard geneticist whose groundbreaking research on epigenetics and NAD+ has fundamentally challenged our understanding of aging, Dr. Sinclair has become one of the most influential voices in longevity science through his acclaimed book Lifespan and extensive academic contributions.`,
    sns: {
      instagram: "https://www.instagram.com/davidsinclairphd/",
      x: "https://twitter.com/davidasinclair",
    },
  },
  {
    name: "Andrew Huberman",
    specialty: "Neuroscientist & Stanford professor",
    image: "/people/andrew.jpg",
    stacks: [
      "Huberman Sleep Stack",
      "Huberman Hormone Support",
      "Huberman Focus & Stress",
      "Huberman Performance",
    ],
    supplements: [
      "Magnesium Threonate",
      "Apigenin",
      "L-Theanine",
      "Tongkat Ali",
      "Fadogia Agrestis",
      "Creatine",
      "Omega-3",
      "Rhodiola Rosea",
      "Vitamin D3",
      "Zinc",
      "Probiotics",
    ],
    cardSupplements: [
      "Magnesium Threonate",
      "Apigenin",
      "L-Theanine",
      "Tongkat Ali",
      "Omega-3",
    ],
    coveredCategories: [
      "Sleep Optimization",
      "Cognitive Enhancement",
      "Metabolic & Weight",
      "Longevity & Immune",
      "Beauty / Inner Glow",
      "Energy Boost",
    ],
    bio: `Stanford's renowned neuroscientist who has revolutionized science communication, Dr. Huberman translates complex brain research into practical wellness strategies through his wildly successful podcast, reaching millions with evidence-based approaches to optimize human performance.`,
    sns: {
      instagram: "https://www.instagram.com/hubermanlab/",
      x: "https://twitter.com/hubermanlab",
    },
  },
  {
    name: "Mark Hyman",
    specialty: "Functional medicine pioneer",
    image: "/people/mark.jpg",
    stacks: [
      "Hyman Foundational Wellness",
      "Hyman Metabolic Balance",
      "Hyman Detox Support",
      "Hyman Gut Health",
    ],
    supplements: [
      "Multivitamin",
      "Omega-3",
      "Magnesium",
      "Vitamin D3",
      "Vitamin K2",
      "NAC",
      "CoQ10",
      "Probiotics",
      "Curcumin",
      "Alpha-lipoic acid",
      "Resveratrol",
      "Berberine",
      "Glutathione",
    ],
    cardSupplements: ["Multivitamin", "Omega-3", "Magnesium", "Vitamin D3"],
    coveredCategories: [
      "Longevity & Immune",
      "Beauty / Inner Glow",
      "Sleep Optimization",
      "Cognitive Enhancement",
      "Energy Boost",
      "Metabolic & Weight",
    ],
    bio: `A visionary physician who transformed modern medicine through functional approaches, Dr. Hyman has authored numerous bestsellers while pioneering the food-as-medicine movement, demonstrating how systems biology can reverse chronic disease and promote longevity.`,
    sns: {
      instagram: "https://www.instagram.com/drmarkhyman/",
      x: "https://twitter.com/drmarkhyman",
    },
  },
  {
    name: "Gary Brecka",
    specialty: "Human biologist (The Ultimate Human)",
    image: "/people/Gary-Brecka.jpg",
    stacks: [
      "Brecka Methylation",
      "Brecka Antioxidant",
      "Brecka Performance",
      "Brecka Gut & Immune",
    ],
    supplements: [
      "Methylated B-Complex",
      "Vitamin D3 + K2",
      "Glutathione",
      "CoQ10",
      "Magnesium",
      "Omega-3",
      "Probiotics",
      "Curcumin",
      "Vitamin C",
      "Zinc",
      "L-Arginine",
    ],
    cardSupplements: [
      "Methylated B-Complex",
      "Vitamin D3 + K2",
      "Glutathione",
      "CoQ10",
    ],
    coveredCategories: [
      "Longevity & Immune",
      "Cognitive Enhancement",
      "Metabolic & Weight",
      "Beauty / Inner Glow",
      "Energy Boost",
      "Sleep Optimization",
    ],
    bio: `An innovative human biologist and performance specialist, Brecka has established himself as a leading authority in genetic optimization, using his company The Ultimate Human to help individuals unlock their biological potential through personalized health protocols.`,
    sns: {
      instagram: "https://www.instagram.com/garybrecka/",
      x: "https://twitter.com/garybrecka",
    },
  },
  {
    name: "Eric Verdin",
    specialty: "CEO, Buck Institute",
    image: "/people/Eric.verdin.jpg",
    stacks: [
      "Verdin Longevity Basics",
      "Verdin Mito Performance",
      "Verdin Antioxidant",
      "Verdin Gut Support",
    ],
    supplements: [
      "Vitamin D3",
      "Vitamin B12",
      "Omega-3",
      "Creatine",
      "Magnesium",
      "NAC",
      "CoQ10",
      "Polyphenol blend",
      "Probiotics",
    ],
    cardSupplements: ["Vitamin D3", "Vitamin B12", "Omega-3", "Creatine"],
    coveredCategories: [
      "Longevity & Immune",
      "Cognitive Enhancement",
      "Energy Boost",
      "Beauty / Inner Glow",
      "Sleep Optimization",
      "Metabolic & Weight",
    ],
    bio: `A distinguished Belgian geroscientist who has shaped the global aging research landscape, Dr. Verdin leads the prestigious Buck Institute for Research on Aging, driving innovative studies that bridge laboratory discoveries with clinical applications for human healthspan extension.`,
    sns: {
      instagram: "https://www.instagram.com/buckinstitute/",
      x: "https://twitter.com/ericverdin",
    },
  },
];
